      - name: Generate Test.js with Claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          node <<'EOF'
          import fs from "fs";
          import Anthropic from "@anthropic-ai/sdk";

          const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

          const prompt = `
          Erzeuge eine kleine JavaScript-Datei Test.js.
          Inhalt: module.exports = { message: "Hallo von Claude!" };
          Ausgabe nur gültiger JS-Code, keine Erklärungen.
          `;

          const run = async () => {
            const resp = await client.messages.create({
              model: "claude-3-5-sonnet-20241022",
              max_tokens: 200,
              messages: [{ role: "user", content: prompt }]
            });

            const content = resp.content[0].text;
            fs.writeFileSync("aiduino/extension/out/config/Test.js", content);
            console.log("✅ Test.js von Claude generiert");
          };

          run().catch(err => {
            console.error("❌ Fehler beim Generieren:", err);
            process.exit(1);
          });
          EOF

