name: Update Provider Configs with Claude
on: workflow_dispatch
jobs:
  update-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Update configs with Claude
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        curl -X POST https://api.anthropic.com/v1/messages \
          -H "x-api-key: $ANTHROPIC_API_KEY" \
          -H "anthropic-version: 2023-06-01" \
          -H "content-type: application/json" \
          -d '{"model": "claude-3-5-sonnet-20241022", "max_tokens": 4000, "messages": [{"role": "user", "content": "Generate a complete providerConfigs.js file with latest models and prices for Claude, ChatGPT, Gemini, Groq, Mistral, Perplexity, Cohere. Use CONFIG_VERSION with today in DDMMYY format. Return only JavaScript code."}]}'
